/**
 * Envelope Zod schemas — mirrors the envelope section of
 * python/tests/passport/test_envelope_tier_agent_id.py (6 tests).
 *
 * The canonicalization round-trip test pins three-way byte-equality across
 * backend ↔ Python ↔ TS: the expected hex literal is byte-copied from the
 * Python test (lines 287–307), which was generated by `jcs.canonicalize` on
 * the same fixture dict. Any drift here is a spec-parity bug.
 */

import { describe, expect, it } from 'vitest';

import { canonicalizeStrict } from '../src/passport/canonical.js';
import { envelopeSchema } from '../src/passport/envelope.js';

const VALID_ENVELOPE_DICT = {
  schema_version: 2,
  passport_id: 'pp_test_00000001',
  identity: {
    agent_id: 'agent_self_Zmh6rfhivXdsj8GLjp-OIAiXFIVu4jOz',
    agent_name: 'alice@dev.local',
    public_key: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=',
  },
  permissions: [
    {
      permission_key: 'flights:book',
      constraints: { max_per_action_cost: 500 },
    },
  ],
  provenance: {
    issuer: { type: 'self', id: 'self:abc123', key_id: 'self' },
    gate_id: null,
    catalog_content_hash: null,
    catalog_version: null,
    delegation_chain: null,
    issued_at: '2026-04-22T00:00:00Z',
    expires_at: '2026-05-22T00:00:00Z',
  },
  delegation_authority: false,
  verification_evidence: [],
};

describe('envelopeSchema', () => {
  it('parses a valid self-issued minimal envelope', () => {
    const env = envelopeSchema.parse(VALID_ENVELOPE_DICT);
    expect(env.schema_version).toBe(2);
    expect(env.provenance.issuer.type).toBe('self');
  });

  it('rejects unknown top-level field', () => {
    const bad = { ...VALID_ENVELOPE_DICT, unknown_field: 'surprise' };
    expect(() => envelopeSchema.parse(bad)).toThrow();
  });

  it.each([1, 3, '2'])('rejects schema_version=%j (not literal 2)', (badVersion) => {
    const bad = { ...VALID_ENVELOPE_DICT, schema_version: badVersion };
    expect(() => envelopeSchema.parse(bad)).toThrow();
  });

  it('requires delegation_authority', () => {
    const { delegation_authority: _omit, ...bad } = VALID_ENVELOPE_DICT;
    void _omit;
    expect(() => envelopeSchema.parse(bad)).toThrow();
  });

  it('requires verification_evidence', () => {
    const { verification_evidence: _omit, ...bad } = VALID_ENVELOPE_DICT;
    void _omit;
    expect(() => envelopeSchema.parse(bad)).toThrow();
  });

  it('canonicalization round-trip is byte-stable across parse', () => {
    // Primary assertion: Zod parse + canonicalize must equal source-dict
    // canonicalize. Proves no silent field reordering, reformatting, or
    // hidden adds during schema validation.
    const env = envelopeSchema.parse(VALID_ENVELOPE_DICT);
    const actualViaParse = canonicalizeStrict(env);
    const expectedFromSource = canonicalizeStrict(VALID_ENVELOPE_DICT);

    expect(Buffer.from(actualViaParse).equals(Buffer.from(expectedFromSource))).toBe(true);

    // Secondary assertion: source-dict canonical form must match the
    // pre-computed hex baked into the Python suite. Three-way parity lock
    // across backend ↔ Python ↔ TS. Any change here signals a canonicalizer
    // or fixture drift that demands attention.
    const expectedHex =
      '7b2264656c65676174696f6e5f617574686f72697479223a66616c73652c2269' +
      '64656e74697479223a7b226167656e745f6964223a226167656e745f73656c66' +
      '5f5a6d683672666869765864736a38474c6a702d4f4941695846495675346a4f' +
      '7a222c226167656e745f6e616d65223a22616c696365406465762e6c6f63616c' +
      '222c227075626c69635f6b6579223a2241414141414141414141414141414141' +
      '4141414141414141414141414141414141414141414141414141413d227d2c22' +
      '70617373706f72745f6964223a2270705f746573745f3030303030303031222c' +
      '227065726d697373696f6e73223a5b7b22636f6e73747261696e7473223a7b22' +
      '6d61785f7065725f616374696f6e5f636f7374223a3530307d2c227065726d69' +
      '7373696f6e5f6b6579223a22666c69676874733a626f6f6b227d5d2c2270726f' +
      '76656e616e6365223a7b22636174616c6f675f636f6e74656e745f6861736822' +
      '3a6e756c6c2c22636174616c6f675f76657273696f6e223a6e756c6c2c226465' +
      '6c65676174696f6e5f636861696e223a6e756c6c2c22657870697265735f6174' +
      '223a22323032362d30352d32325430303a30303a30305a222c22676174655f69' +
      '64223a6e756c6c2c226973737565645f6174223a22323032362d30342d323254' +
      '30303a30303a30305a222c22697373756572223a7b226964223a2273656c663a' +
      '616263313233222c226b65795f6964223a2273656c66222c2274797065223a22' +
      '73656c66227d7d2c22736368656d615f76657273696f6e223a322c2276657269' +
      '6669636174696f6e5f65766964656e6365223a5b5d7d';
    expect(Buffer.from(actualViaParse).equals(Buffer.from(expectedHex, 'hex'))).toBe(true);
  });
});
